version: "3.9"
services:
  snapsshare-opengraph:
    container_name: snapsshare-opengraph
    image: snapsshare-opengraph:v1.1
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 80
    ports:
      - 80:80
    networks:
      - snapsshare-net
networks:
  snapsshare-net:
    name: snapsshare-net
    external: true
